journal/urls.py
from django.urls import path

from . import views

app_name = "journal"
urlpatterns = [
    path("", views.index_page, name="index"),
    path("students/", views.students_page, name="students"),
    path("change_students/<str:field>", views.change_students, name="change_students"),
    path("lessons/", views.lessons_page, name="lessons"),
    path("change_lessons/<str:field>", views.change_lessons, name="change_lessons"),
    path("tasks/", views.tasks_page, name="tasks"),
    path("change_tasks/<str:field>", views.change_tasks, name="change_tasks"),
    path("attendance/", views.attendance_page, name="attendance"),
    path("change_attendance/", views.change_attendance, name="change_attendance"),
    path("progress/", views.progress_page, name="progress"),
    path("change_progress/", views.change_progress, name="change_progress"),
    path("rating/", views.rating_page, name="rating"),
]

teaching/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('journal/', include('journal.urls')),
    path('admin/', admin.site.urls),
]

journal/views.py
from django.shortcuts import render, get_object_or_404

import datetime
import sys
from django.http import HttpResponse, Http404
from django.template import loader
from django.views import generic
from django.core import serializers
from django.shortcuts import redirect

from .models import Semester, Student, Group, StudyingStudent, Discipline, Task, TaskInGroup, Lesson, LessonInGroup, \
    Attendance, Progress, ControlPoint, Rating
from .commondata import Data


def extract_value_and_position(request):
    newValue = request.POST.get("newValue", None)
    position = request.POST.get("position", None)
    if newValue is not None and position is not None:
        position = int(position)
    return newValue, position


def index_page(request):
    Data.prepare_data(request.POST)
    context = {"common_data": Data.common_data, "week_num": 1}
    return render(request, "journal/index.html", context=context)


def students_page(request):
    Data.prepare_data(request.POST)
    Data.init_studying_students()
    if Data.common_data["current_semester"] is not None:
        context = {"common_data": Data.common_data, "studying_students": Data.studying_students}
        return render(request, "journal/students.html", context=context)
    else:
        request.POST = []
        return index_page(request)


def change_students(request, field):
    newValue, position = extract_value_and_position(request)
    if newValue is not None and position is not None:
        id = Data.studying_students[position].student.id
        student = Student.objects.filter(id=id)[0]
        if field == "expelled":
            newValue = newValue == "true"
        setattr(student, field, newValue)
        student.save()
        return HttpResponse("CHANGE")
    else:
        return redirect("journal:students")


def lessons_page(request):
    Data.prepare_data(request.POST)
    Data.init_lessons_in_group()
    if Data.common_data["current_semester"] is not None:
        context = {"common_data": Data.common_data, "lessons": Data.lessons}
        return render(request, "journal/lessons.html", context=context)
    else:
        request.POST = []
        return index_page(request)


def change_lessons(request, field):
    newValue, position = extract_value_and_position(request)
    if newValue is not None and position is not None:
        id = Data.lessons[position].id
        lesson = Lesson.objects.filter(id=id)[0]
        setattr(lesson, field, newValue)
        lesson.save()
        return HttpResponse("CHANGE")
    else:
        return redirect("journal:tasks")


def tasks_page(request):
    Data.prepare_data(request.POST)
    Data.init_tasks_in_group()
    if Data.common_data["current_semester"] is not None:
        context = {"common_data": Data.common_data, "tasks": Data.tasks}
        return render(request, "journal/tasks.html", context=context)
    else:
        request.POST = []
        return index_page(request)


def change_tasks(request, field):
    newValue, position = extract_value_and_position(request)
    if newValue is not None and position is not None:
        id = Data.tasks[position].id
        task = Task.objects.filter(id=id)[0]
        setattr(task, field, newValue)
        task.save()
        return HttpResponse("CHANGE")
    else:
        return redirect("journal:tasks")


def attendance_page(request):
    Data.prepare_data(request.POST)
    Data.init_attendance()
    if Data.common_data["current_semester"] is not None:
        context = {"common_data": Data.common_data, "lessons": Data.lessons, "studying_students": Data.studying_students,
                   "attendance": Data.attendance}
        return render(request, "journal/attendance.html", context=context)
    else:
        request.POST = []
        return index_page(request)


def change_attendance(request):
    newValue = request.POST.get("newValue", None)
    student_position = request.POST.get("student_position", None)
    lesson_id = request.POST.get("lesson_id", None)
    if (newValue is not None) and (student_position is not None) and (lesson_id is not None):
        student_position = int(student_position)
        lesson_id = int(lesson_id)
        student_id = Data.studying_students[student_position].student.id
        ss = StudyingStudent.objects.filter(student__id=student_id)[0]
        lg = LessonInGroup.objects.filter(lesson__id=lesson_id, subgroup_number=ss.subgroup_number)[0]
        attendance = Attendance.objects.filter(studying_student=ss, lesson_in_group=lg)
        attendance = attendance[0]
        attendance.mark = newValue
        attendance.save()
        return HttpResponse("CHANGE")
    else:
        return redirect("journal:attendance")


def progress_page(request):
    Data.prepare_data(request.POST)
    Data.init_progress()
    if Data.common_data["current_semester"] is not None:
        context = {"common_data": Data.common_data, "tasks": Data.tasks, "studying_students": Data.studying_students,
                   "progress": Data.progress}
        return render(request, "journal/progress.html", context=context)
    else:
        request.POST = []
        return index_page(request)


def change_progress(request):
    newValue = request.POST.get("newValue", None)
    student_position = request.POST.get("student_position", None)
    task_id = request.POST.get("task_id", None)
    if (newValue is not None) and (student_position is not None) and (task_id is not None):
        student_position = int(student_position)

        task_id = int(task_id)
        student_id = Data.studying_students[student_position].student.id
        ss = StudyingStudent.objects.filter(student__id=student_id)[0]
        tg = TaskInGroup.objects.filter(task__id=task_id, subgroup_number=ss.subgroup_number)[0]
        progress = Progress.objects.filter(studying_student=ss, task_in_group=tg)
        progress = progress[0]

        if newValue == "":
            progress.passed = False
            progress.grade = None
            progress.delivery_date = None
        else:
            progress.passed = True
            try:
                space_index = newValue.index(" ")
                date_string = newValue[space_index + 1:]
                grade_string = newValue[1:space_index - 1]
            except ValueError:
                date_string = newValue
                grade_string = None

            if grade_string is None:
                progress.grade = None
            else:
                progress.grade = int(grade_string)
            progress.delivery_date = datetime.datetime.strptime(date_string, "%Y-%m-%d")
        progress.save()
        return HttpResponse("CHANGE")
    else:
        return redirect("journal:progress")


def rating_page(request):
    Data.prepare_data(request.POST)
    Data.init_rating()
    if Data.common_data["current_semester"] is not None:
        context = {"common_data": Data.common_data, "control_points": Data.control_points,
                   "studying_students": Data.studying_students, "rating": Data.rating}
        return render(request, "journal/rating.html", context=context)
    else:
        request.POST = []
        return index_page(request)

journal/templates/journal/attendance.html
{% extends "journal/base.html" %}

{% block link %} action="{% url "journal:attendance" %}" {% endblock %}

{% block working_area %}
    <script>
        document.getElementById("nav-attendance").classList.add("active");

        let prepareAttendance = (cell) => {
            const newValue = cell._cell.value;
            const student_position = table.getRowPosition(cell._cell.row, false);
            const lesson_id = cell.getColumn().getField();
            const formData = new FormData();
            formData.append('newValue', newValue);
            formData.append('student_position', student_position);
            formData.append('lesson_id', lesson_id);
            const csrftoken = document.cookie.replace(/(?:(?:^|.*;\s*)csrftoken\s*\=\s*([^;]*).*$)|^.*$/, "$1");
            const headers = {"X-CSRFToken": csrftoken};
            const body = formData;
            return {headers, body};
        };

        let tabledata = []
        {% for ss in studying_students %}
            tabledata.push(
                {
                    "num": {{ forloop.counter}},
                    "student": "{{ ss.student.journal_name }}"
                }
            )
        {%  endfor %}

        let table = new Tabulator("#example-table", {
            height: "85vh",
            data: tabledata,
            layout: "fitData",
            columns: [
                {title: "№", field: "num", sorter: "number", hozAlign: "center", frozen: true},
                {title: "ФИО", field: "student", sorter: "string", frozen: true},
            ]
        });

        let curr_row;
        {% for row in attendance %}
            curr_row = tabledata[{{ forloop.counter0 }}];
            {% for k,v in row.items %}
                curr_row["{{ k }}"] = "{{ v }}";
            {% endfor %}
        {% endfor %}

        {%  for lesson in lessons %}
            table.addColumn({
                title: "{{ lesson.abbreviation }}<br>{{ lesson.date_fact|date:"d.m" }}",
                field: "{{ lesson.id }}",
                hozAlign: "center", headerSort: false,
                formatter: (cell, formatterParams, onRendered) => {
                    value = cell.getValue();
                    if (value === undefined)
                        cell.getElement().style.backgroundColor = "gray";
                    else if (value === "+") {
                        cell.getElement().style.color = "green";
                        cell.getElement().style.fontWeight = "bold";
                    } else if (value === "н") {
                        cell.getElement().style.color = "red";
                        cell.getElement().style.fontWeight = "bold";
                    } else if (value === "оп") {
                        cell.getElement().style.color = "purple";
                        cell.getElement().style.fontWeight = "bold";
                    } else if (value === "н(у)") {
                        cell.getElement().style.color = "blue";
                        cell.getElement().style.fontWeight = "bold";
                    }
                    return cell.getValue();
                },
                cellClick: async (e, cell) => {
                    if (!e.ctrlKey && !e.altKey) return;
                    if (cell.getValue() === undefined) return;
                    if (e.ctrlKey) {
                        switch (cell.getValue()) {
                            case "":
                                cell.setValue("+");
                                break;
                            case "+":
                                cell.setValue("н");
                                break;
                            case "н":
                                cell.setValue("оп");
                                break;
                            case "оп":
                                cell.setValue("н(у)");
                                break;
                            case "н(у)":
                                cell.setValue("");
                                break;
                        }
                    }
                    else {
                        switch (cell.getValue()) {
                            case "":
                                cell.setValue("н(у)");
                                break;
                            case "+":
                                cell.setValue("");
                                break;
                            case "н":
                                cell.setValue("+");
                                break;
                            case "оп":
                                cell.setValue("н");
                                break;
                            case "н(у)":
                                cell.setValue("оп");
                                break;
                        }
                    }
                    res = prepareAttendance(cell);
                    let response = await fetch("{% url "journal:change_attendance" %}", {
                        method: "POST", credentials: 'include', headers: res["headers"],
                        body: res["body"]
                    });
                }
            })
        {%  endfor %}
    </script>
{% endblock %}

journal/templates/journal/base.html
{% load static %}

<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css"
          integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <link href="https://unpkg.com/tabulator-tables@4.7.2/dist/css/tabulator.min.css" rel="stylesheet">
    <script type="text/javascript" src="https://unpkg.com/tabulator-tables@4.7.2/dist/js/tabulator.min.js"></script>
    <script type="text/javascript" src="{% static 'journal/utils.js' %}"></script>
    <title>Журнал</title>

</head>

<body>
<div class="container-fluid">

    <nav class="navbar navbar-expand-md navbar-dark sticky-top bg-dark">
        <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarCollapse"
                aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item" id="nav-students">
                    <a class="nav-link" href="{% url "journal:students" %}">Студенты<span class="sr-only"></span></a>
                </li>
                <li class="nav-item" id="nav-lessons">
                    <a class="nav-link" href="{% url "journal:lessons" %}">Занятия</a>
                </li>
                <li class="nav-item" id="nav-tasks">
                    <a class="nav-link" href="{% url "journal:tasks" %}">Задания</a>
                </li>
                <li class="nav-item" id="nav-attendance">
                    <a class="nav-link" href="{% url "journal:attendance" %}">Посещаемость</a>
                </li>
                <li class="nav-item" id="nav-progress">
                    <a class="nav-link" href="{% url "journal:progress" %}">Успеваемость</a>
                </li>
                <li class="nav-item" id="nav-rating">
                    <a class="nav-link" href="{% url "journal:rating" %}">Рейтинг</a>
                </li>
            </ul>
            <form
                    class="form-inline mt-2 mt-md-0" id="nav-form" method="post"
                    {% block link %} action="{% url "journal:index" %}" {% endblock %}
            >
                {% csrf_token %}
                <select class="form-control" id="semester-select" name="semester" style="margin-right: 1em">
                    {% for semester in common_data.semesters %}
                        <option id="semester_{{ semester.id }}" value="{{ semester.id }}"
                                {% if semester == common_data.current_semester %}
                                selected
                                {% endif %}
                        >
                            {{ semester }}
                        </option>

                    {% endfor %}
                </select>
                <select class="form-control" id="discipline-select" name="discipline" style="margin-right: 1em">
                    {% for discipline in common_data.disciplines %}
                        <option id="discipline_{{ discipline.id }}" value="{{ discipline.id }}"
                                {% if discipline == common_data.current_discipline %}
                                selected
                                {% endif %}
                        >
                            {{ discipline.short_name }}
                        </option>
                    {% endfor %}
                </select>
                <select class="form-control" id="group-select" name="group" style="margin-right: 1em">
                    {% for group in common_data.groups %}
                        <option id="group_{{ group.id }}" value="{{ group.id }}"
                                {% if group == common_data.current_group %}
                                selected
                                {% endif %}
                        >
                            {{ group.group_number }}
                        </option>
                    {% endfor %}
                </select>
                <input class="form-control" type="date" id="date" name="date"
                       value= {{ common_data.current_date|date:"Y-m-d" }}>
            </form>
        </div>
    </nav>

    <footer class="footer mt-auto py-3">
        <div id="example-table">
            {% block working_area %}
            {% endblock %}
        </div>
    </footer>

</div>


<script>
    let ids = ["semester-select", "discipline-select", "group-select", "date"]
    for (let id of ids) {
        document.getElementById(id).onchange = (event) => {
            document.getElementById("nav-form").submit();
        }
    }
</script>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"
        integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"
        integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k"
        crossorigin="anonymous"></script>




</body>

</html>

journal/templates/journal/index.html
{% extends "journal/base.html" %}

{% block link %} action="{% url "journal:index" %}" {% endblock %}

{% block working_area %}

{#<button type="button" class="btn btn-secondary">1</button>#}
    <script>
        /*for (let i=1; i<=16; i++) {
            btn = document.createElement("button");
            document.getElementById("example-table").append(btn);
            btn.type = "button";
            btn.classList.add("btn");
            if (i=={{ week_num }})
                btn.classList.add("btn-primary");
            else
                btn.classList.add("btn-secondary");
            btn.innerText = i;
            btn.style.paddingRight="2";
        }*/
    </script>

{% endblock %}

journal/templates/journal/lessons.html
{% extends "journal/base.html" %}

{% block link %} action="{% url "journal:lessons" %}" {% endblock %}

{% block working_area %}
    <script>
        document.getElementById("nav-lessons").classList.add("active")

        let tabledata = [
            {% for lesson in lessons %}
                {
                    num: {{ forloop.counter }},
                    date_plan: "{{ lesson.date_plan|date:"Y-m-d" }}",
                    date_fact: "{{ lesson.date_fact|date:"Y-m-d" }}",
                    topic: "{{ lesson.topic }}",
                    abbreviation: "{{ lesson.abbreviation }}",
                    lesson_kind: "{{ lesson.lesson_kind }}",
                    comments: "{{ lesson.comments }}",
                    lesson_coef: "{{ lesson.lesson_coef }}",
                },
            {% endfor %}
        ];

        let table = new Tabulator("#example-table", {
            data: tabledata,
            layout: "fitData",
            groupBy: "lesson_kind",
            columns: [
                //{title: "№", field: "num", sorter: "number",},
                /*{
                    title: "Вид", field: "lesson_kind", sorter: "string", editor: false, hozAlign: "center",
                },*/
                {
                    title: "Сокр.", field: "abbreviation", sorter: "string", editor: true, hozAlign: "center",
                    cellEdited: async function (cell) {
                        res = prepare(cell)
                        let response = await fetch("{% url "journal:change_lessons" "abbreviation" %}", {
                            method: "POST", credentials: 'include', headers: res["headers"],
                            body: res["body"]
                        })
                    },
                },
                {
                    title: "Дата (план)", field: "date_plan", sorter: "date", editor: false, hozAlign: "center",
                    sorterParams: {
                        format: "YYYY-MM-DD", alignEmptyValues: "top",
                        formatter: "datetime", formatterParams: {
                            inputFormat: "YYYY-MM-DD",
                            outputFormat: "YYYY-MM-DD",
                            invalidPlaceholder: "(invalid date)"
                        }
                    }
                },
                {
                    title: "Дата (факт)", field: "date_fact", sorter: "date", editor: dateEditor, hozAlign: "center",
                    sorterParams: {
                        format: "YYYY-MM-DD", alignEmptyValues: "top",
                        formatter: "datetime", formatterParams: {
                            inputFormat: "YYYY-MM-DD",
                            outputFormat: "YYYY-MM-DD",
                            invalidPlaceholder: "(invalid date)"
                        }
                    },
                    cellEdited: async function (cell) {
                        res = prepare(cell)
                        let response = await fetch("{% url "journal:change_lessons" "date_fact" %}", {
                            method: "POST", credentials: 'include', headers: res["headers"],
                            body: res["body"]
                        })
                    },
                },
                {
                    title: "Тема", field: "topic", sorter: "string", editor: true,
                    cellEdited: async function (cell) {
                        res = prepare(cell)
                        let response = await fetch("{% url "journal:change_lessons" "topic" %}", {
                            method: "POST", credentials: 'include', headers: res["headers"],
                            body: res["body"]
                        })
                    },
                },
                {
                    title: "Комментарии", field: "comments", sorter: "string", editor: true,
                    cellEdited: async function (cell) {
                        res = prepare(cell)
                        let response = await fetch("{% url "journal:change_lessons" "comments" %}", {
                            method: "POST", credentials: 'include', headers: res["headers"],
                            body: res["body"]
                        })
                    },
                },
                {
                    title: "Коэф.", field: "lesson_coef", sorter: "number", editor: true, hozAlign: "center",
                    cellEdited: async function (cell) {
                        res = prepare(cell)
                        let response = await fetch("{% url "journal:change_lessons" "lesson_coef" %}", {
                            method: "POST", credentials: 'include', headers: res["headers"],
                            body: res["body"]
                        })
                    },
                },
            ],
        });
    </script>
{% endblock %}


journal/templates/journal/progress.html
{% extends "journal/base.html" %}

{% block link %} action="{% url "journal:progress" %}" {% endblock %}

{% block working_area %}
    <script>
        document.getElementById("nav-progress").classList.add("active");

        let prepareProgress = (cell) => {
            const newValue = cell._cell.value;
            const student_position = table.getRowPosition(cell._cell.row, false);
            const task_id = cell.getColumn().getField();
            const formData = new FormData();
            formData.append('newValue', newValue);
            formData.append('student_position', student_position);
            formData.append('task_id', task_id);
            const csrftoken = document.cookie.replace(/(?:(?:^|.*;\s*)csrftoken\s*\=\s*([^;]*).*$)|^.*$/, "$1");
            const headers = {"X-CSRFToken": csrftoken};
            const body = formData;
            return {headers, body};
        };

        let tabledata = []
        {% for ss in studying_students %}
            tabledata.push(
                {
                    "num": {{ forloop.counter}},
                    "student": "{{ ss.student.journal_name }}"
                }
            )
        {%  endfor %}

        let table = new Tabulator("#example-table", {
            height: "85vh",
            data: tabledata,
            layout: "fitData",
            columns: [
                {title: "№", field: "num", sorter: "number", hozAlign: "center", frozen: true},
                {title: "ФИО", field: "student", sorter: "string", frozen: true},
            ]
        });

        let curr_row;
        let value;
        {% for row in progress %}
            curr_row = tabledata[{{ forloop.counter0 }}];
            {% for k,v in row.items %}
                {% if v.passed == False %}
                    value = "";
                {% elif v.grade == None %}
                    value = "{{ v.delivery_date|date:"Y-m-d" }}"
                {% else %}
                    value = "({{ v.grade }}) {{ v.delivery_date|date:"Y-m-d" }}"
                {% endif %}
                curr_row["{{ k }}"] = value;
            {% endfor %}
        {% endfor %}

        {%  for task in tasks %}
            table.addColumn({
                title: "{{ task.abbreviation }}<br>{{ task.deadline|date:"d.m" }}",
                field: "{{ task.id }}",
                hozAlign: "center", headerSort: false,
                formatter: (cell, formatterParams, onRendered) => {
                    value = cell.getValue();
                    if (value === undefined)
                        cell.getElement().style.backgroundColor = "gray";
                    else {
                        const space_index = value.indexOf(" ");
                        let str_delivery_date;
                        if (space_index !== -1)
                            str_delivery_date = value.slice(space_index + 1);
                        else
                            str_delivery_date = value;
                        const delivery_date = Date.parse(str_delivery_date);
                        const deadline = Date.parse("{{ task.deadline|date:"Y-m-d" }}");
                        if (delivery_date <= deadline) {
                            cell.getElement().style.color = "green";
                        } else {
                            cell.getElement().style.color = "red";
                        }
                        cell.getElement().style.fontWeight = "bold";
                    }
                    return cell.getValue();
                },
                cellClick: async (e, cell) => {
                    if (!e.ctrlKey && !e.altKey) return;
                    if (cell.getValue() === undefined) return;
                    if (e.ctrlKey) {
                        if (cell.getValue() === "")
                            cell.setValue("{{ common_data.current_date|date:"Y-m-d" }}");
                        else
                            cell.setValue("");
                    } else {
                        let grade = prompt("Оценка", "5");
                        if (grade === null || grade === undefined || grade === "") return
                        grade = Number(grade);
                        if (grade === null || grade === undefined || isNaN(grade)) return
                        cell.setValue(`(${grade}) {{ common_data.current_date|date:"Y-m-d" }}`);
                    }

                    res = prepareProgress(cell);
                    let response = await fetch("{% url "journal:change_progress" %}", {
                        method: "POST", credentials: 'include', headers: res["headers"],
                        body: res["body"]
                    });
                }

            })
        {%  endfor %}
    </script>
{% endblock %}

journal/templates/journal/rating.html
{% extends "journal/base.html" %}

{% block link %} action="{% url "journal:rating" %}" {% endblock %}

{% block working_area %}
    <script>
        document.getElementById("nav-rating").classList.add("active");

        let tabledata = []
        {% for ss in studying_students %}
            tabledata.push(
                {
                    "num": {{ forloop.counter}},
                    "student": "{{ ss.student.journal_name }}"
                }
            )
        {%  endfor %}

        let table = new Tabulator("#example-table", {
            height: "85vh",
            data: tabledata,
            layout: "fitData",
            columns: [
                {title: "№", field: "num", sorter: "number", hozAlign: "center", frozen: true},
                {title: "ФИО", field: "student", sorter: "string", frozen: true},
            ]
        });

        let curr_row;
        {% for row in rating %}
            curr_row = tabledata[{{ forloop.counter0 }}];
            {% for k,v in row.items %}
                curr_row["{{ k }}"] = "{{ v }}";
            {% endfor %}
        {% endfor %}

        {%  for control_point in control_points %}
            table.addColumn({
                title: "{{ control_point.max_score }}<br>{{ control_point.date|date:"d.m" }}",
                field: "{{ control_point.id }}",
                hozAlign: "center", headerSort: false,
            })
        {%  endfor %}
    </script>
{% endblock %}